In [96]:
import pandas as pd
import re

In [97]:
# Load the dataset using pandas
df = pd.read_csv('./davidson_labeled_data.csv', index_col=0)

In [98]:
# 24783 lignes
df.shape

(24783, 6)

In [99]:
df.tail()

,count,hate_speech,offensive_language,neither,class,tweet
25291,3,0,2,1,1,you's a muthaf***in lie &#8220;@LifeAsKing: @2...
25292,3,0,1,2,2,"you've gone and broke the wrong heart baby, an..."
25294,3,0,3,0,1,young buck wanna eat!!.. dat nigguh like I ain...
25295,6,0,6,0,1,youu got wild bitches tellin you lies
25296,3,0,0,3,2,~~Ruffled | Ntac Eileen Dahlia - Beautiful col...

In [100]:
df.drop(columns=["count", "hate_speech", "offensive_language", "neither"], inplace=True)

In [101]:
df.reset_index(drop=True, inplace = True)

In [102]:
df.tail()

       class                                              tweet
24778      1  you's a muthaf***in lie &#8220;@LifeAsKing: @2...
24779      2  you've gone and broke the wrong heart baby, an...
24780      1  young buck wanna eat!!.. dat nigguh like I ain...
24781      1              youu got wild bitches tellin you lies
24782      2  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...

In [103]:
df.sample(100)

       class                                              tweet
20233      1  RT @trillycjuicy: I'm really chill. I talk to ...
865        1  #porn,#android,#iphone,#ipad,#sex,#xxx, | #Clo...
20335      1  RT @wojtata: Huntley High School is the most r...
21906      1  Thinking that i care dont give a fuck bout you...
17536      1  RT @TRAPMAMA: @_BoobieJohnson so i could catch...
...      ...                                                ...
8576       1  Cute buff guy walked in and then he opened his...
18020      0  RT @WaavyLee: His balls ashy RT @Yattabing: @T...
23680      1  bitches who never knew me now calling me WesGo...
1884       1  &#8220;@robbyohn: The Kimberley story is by fa...
24729      1     ya bitch aint bad nigga, you aint got no taste

[100 rows x 2 columns]

In [104]:
re.sub(r'&#[0-9]+', '', "This is a sample string with emojis like &#8220 and &#128512")

'This is a sample string with emojis like  and '

In [105]:
for i in range(len(df.tweet)):
  t = df.tweet[i]

  # remove "RT"
  t = re.sub(r'\bRT\b',"", t)

  # remove mention @
  t = re.sub(r"@\S+", "", t)

  # remove URL
  t = re.sub("http[s]?\://\S+", "", t)

  # remove emoji "&#"
  t = re.sub(r'&#[0-9]+', '', t)

  # remove extra space
  t = re.sub('\s+',' ', t)

  df.tweet[i] = t

<ipython-input-105-201a697d9b01>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.tweet[i] = t

In [106]:
df.sample(100)

       class                                              tweet
13255      1         New strategy to get bitches: Be Bruno Mars
1330       1  ; "I'm rich......" (Dave Chappelle voice) sign...
555        1  "So he's a good football player...but he still...
18232      1   You don't know maybe some bitches like a man ...
19347      1   ; quote this tweet with the funniest pic in y...
...      ...                                                ...
24607      2                                           trash af
14721      1                       what does the fox say bitch?
14187      1   I bet Beyonce's pussy tastes like a fresh car...
8240       1  Bust a nicca head,smack a hoe and shoot the cl...
8119       1  Blunt to the head, fuck Feds, I eat pussy till...

[100 rows x 2 columns]

In [107]:
df.to_csv("clean_davidson_labeled_data.csv")